# Generated by Django 4.2.4 on 2023-08-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'обычный пользователь'), ('moderator', 'модератор')], default='moderator', verbose_name='роль'),
        ),
    ]
