# Generated by Django 4.2.4 on 2023-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sum',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='цена курса'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='подтверждение платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='id намерения платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='id метода платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cтатус платежа'),
        ),
    ]
